<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container21yrV1l\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container21yrV1l/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container21yrV1l.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container21yrV1l\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container21yrV1l\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '21yrV1l',
    'container.build_id' => '5eeab5a5',
    'container.build_time' => 1545297034,
), __DIR__.\DIRECTORY_SEPARATOR.'Container21yrV1l');
